### ISSUE TITLE
error deploying

### ISSUE THREAD

**Issue by Gert-Jan78** [fabragaMS/ADPE2E#1]
Hi, thx for the training. 

As an old school BI consultant/developer this looks very interesting to me. Unfortunately I can't deploy the solution and am getting an error. My region is west-europe.

thx,
GJ

**Comment by Gert-Jan78** [comment]
I got this error message:
The template deployment '3aaf088b-b9b9-4efb-b99e-e13c121470e8' is not valid according to the validation procedure. The tracking id is 'e3886e3b-ad46-4b85-b5c1-bc7b78259164'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.

**Comment by fabragaMS** [comment]
Hi Gert-Jan78, sorry you got an error message. I've just done the same here on my end deploying the lab to West Europe and it worked well with no issues raised. 

Are you able to confirm whether that you have admin rights on your subscription or whether it has any deployment constraints enabled? Thank you.

**Comment by Gert-Jan78** [comment]
Hi, thx fro the quick reply. Still got the the error, I am indeed admin on my subscription. Could it be because I have a pay per use subscription type?

**Comment by fabragaMS** [comment]
Hummm...interesting. What happens if you try to deploy it to another region. Pick any other from the list available in the deployment page. Let me know how you go. Thanks.

Fabio Braga
Cloud Solution Architect – Data Platform
Office: +61 (7) 3218 7010
Mobile: +61 402 290 501
fabio.braga@microsoft.com
Level 28, 400 George Street
Brisbane QLD 4000
Australia
________________________________

**Comment by Gert-Jan78** [comment]
tried East-US, got the same error message

**Comment by fabragaMS** [comment]
Hi,

I just tried a second deployment and I'm unable to reproduce the problem on my side...all resources were deployed successfully in East US.

Can you provide extra info about your subscription? Are you aware of any policies apied to it that would prevent certain services from being deployed?

When you go the the deployment status of your resource group, do you see a failed deployment there? If so, do you see any extra piece of useful information that could help us figure out what is going on?

**Comment by Gert-Jan78** [comment]
After trying the deployment from the cloud shell I got a more descriptive error message about exceeding the quota. I requetsed a quota increase (https://docs.microsoft.com/en-us/azure/azure-supportability/resource-manager-core-quotas-request) and after that the deployment proceeded.

thanks for the help!

**Comment by Gert-Jan78** [comment]
deployment did now start and then I got a new error message. Have to look into this one. One other question what will be the cost of running this all in Azure?

**Comment by fabragaMS** [comment]
Ok, I'm glad that we are making progress, let me know when you know more about the new message.

As to costs, the estimated a out for two days (duration of the workshop) is $150. But you can minimize it but turning the MDWSQLSERVER and MDWGATEWAY after lab 1 and then pausing SQL Data warehouse after lab 2.

Fabio Braga
Cloud Solution Architect – Data Platform
Office: +61 (7) 3218 7010
Mobile: +61 402 290 501
fabio.braga@microsoft.com
Level 28, 400 George Street
Brisbane QLD 4000
Australia
________________________________
