### ISSUE TITLE
Role of Data Bricks within Solution - Lab 4: Add AI to your Big Data Pipeline with Cognitive Services

### ISSUE THREAD

**Issue by Josh-BI-UK** [fabragaMS/ADPE2E#14]
Hi @fabragaMS,

What an amazing set of labs you have created. Absolutely super valuable. In my efforts to learn how to become a better Azure Analytics Solutions Architecture I had a few questions about your chosen architecture.

In Lab 4: Add AI to your Big Data Pipeline with Cognitive Services:  We use Data Bricks as the platform to call an Azure Computer Vision API. 

Link to lab: https://github.com/fabragaMS/ADPE2E/blob/master/Lab/Lab4/Lab4.md

1. Why have you chosen to use Data Bricks to provide that aspect of the solution?

2. What role would you say Data Bricks is serving within your solution design?

3. Is there other options which could be used (within the Azure eco-system) which perform the same role as Data Bricks for this particular use case?

4. Within the “Create Data Bricks Linked Service in Azure Data Factory” section of the lab we use Data Factory to run our Data Bricks applet/workspace, which calls the Compute Vision service. 

Does that mean the Data Bricks cluster which provide the compute for this aspect must be active indefinitely (or at least as long as we need to use the solution we are implementing)? [link to section within lab: https://github.com/fabragaMS/ADPE2E/blob/master/Lab/Lab4/Lab4.md#create-databricks-linked-service-in-azure-data-factory ]

**Comment by fabragaMS** [comment]
Hey Josh,

I’m glad you enjoyed the labs and I hope you learned a thing or two from them.

As to your question about the use of Databricks to invoke Cognitive Services, yes it is an overkill. A Databricks cluster *is not* required to call Cognitive Services and a call to an Azure Function would do the job, but *for the purposes of the workshop* I did not want to introduce yet another service to the architecture and another set of skills (C#, for example).

The role Databricks play in the overall architecture is of a big data analytics engine. For analogy, what SQL Server is to an .mdf file (database file) Databricks is for the data lake. Data Lake is simply storage, you need a compute engine able to process these files and extract the only the data you need from it, and that’s Databricks job. Hope this makes sense.

Cheers,

Fabio Braga
Senior Cloud Solution Architect – Data & AI
Office: +61 (7) 3218 7010
Mobile: +61 402 290 501
fabio.braga@microsoft.com<mailto:fabio.braga@microsoft.com>

Level 28, 400 George Street
Brisbane QLD 4000
Australia
[cid:image001.png@01D6B805.83C436F0]

**Comment by Josh-BI-UK** [comment]
Fab thank you. Very clear.
