### ISSUE TITLE
error deploying

### ISSUE THREAD

**Issue by ErnestoGueMen** [fabragaMS/ADPE2E#21]
Hello

When I deploy, it's makes error in the "Review & Create" step: 

{"code":"InvalidTemplateDeployment","details":[{"code":"InvalidParameter","target":"imageReference","message":"The following list of images referenced from the deployment template are not found: Publisher: MicrosoftWindowsDesktop, Offer: Windows-10, Sku: rs5-pro, Version: latest. Please refer to https://docs.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage for instructions on finding available images."}],"message":"The template deployment 'Microsoft.Template-20211012172212' is not valid according to the validation procedure. The tracking id is '729a9123-5be9-45a9-97f0-e5655ab6361a'. See inner errors for details."}

------image below---

![image](https://user-images.githubusercontent.com/74374301/137036411-2e86e834-d028-437f-bc49-1714f2a62155.png)
<img width="283" alt="error_deploying_ADPE2E" src="https://user-images.githubusercontent.com/74374301/137036558-c19517b6-2db9-4295-b73f-7a5e11bcdea1.png">

**Comment by EmielStoelinga** [comment]
@ErnestoGueMen You should edit the template by clicking on the "Edit template" button and editing it before clicking on the "Review + create" button.

**Comment by jhasanjay** [comment]
There was a problem in passing the list of images in ADF for calling the function created in Databricks Notebook (Lab 04) - there is a bug in having a space between the image container path and image name. You need to put this in ForEachImage base parameters to fix the spaces- @concat(trim(variables('ImageMetadataContainerUrl')), trim(item().name))
