### ISSUE TITLE
France region is not supported despite the fact that it is listed in recommanded regions

### ISSUE THREAD

**Issue by aguerot** [fabragaMS/ADPE2E#3]
When hitting the deploy button to initiate deployment and select my existing resource group located in France Central I get a message saying that France Central region is not supported.

![image](https://user-images.githubusercontent.com/11557948/62950240-f3fc3d00-bde7-11e9-9892-b3f85775e37c.png)

However ./deploy/deploy.md states that France Central is supported.

![image](https://user-images.githubusercontent.com/11557948/62950300-09716700-bde8-11e9-8b1e-70fcf3bd2d4c.png)

Seems that databricks workspace are not supported in France Central location

Obvious workaround is to switch to another location for my resource group.

rgds

**Comment by fabragaMS** [comment]
Hi agerot, thank you very much for that...good catch. I've updated the list of supported regions to those that support both Databricks and Data Factory. 

Let me know how you go as you progress with your labs. Thank you.
