### ISSUE TITLE
Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 0, Additional requested: 12

### ISSUE THREAD

**Issue by Freewilly3d** [fabragaMS/ADPE2E#4]
{"telemetryId":"beeb0598-e318-44f3-8b81-977d482700a9","bladeInstanceId":"Blade_2aa034b766dd4a1da428a619e9442540_3_0","galleryItemId":"MyGalleryItem","createBlade":"DeployToAzure","code":"InvalidTemplateDeployment","message":"The template deployment 'bill_moderndw.net.mdw-lab' is not valid according to the validation procedure. The tracking id is 'b4967577-95eb-4e30-9001-d08a75dddf80'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.","details":[{"code":"QuotaExceeded","message":"Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 0, Additional requested: 12. Please read more about quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/{\"subId\":\"f2b5de09-a02a-45a6-b5eb-dab4b57ac6d2\",\"pesId\":\"15621\",\"supportTopicId\":\"32447243\"}."}]}

What do I need to request?

**Comment by Freewilly3d** [comment]
I uping my cores to 20 to get through the lessons.
I ended up taking the json and running on the portal.  the other problem I ran into was MDWComputervision setup failed with name contains reserved word error?

**Comment by fabragaMS** [comment]
Hi Freewilly3d, I'm glad you got the template to work in the end. I've tried to redeploy the template but I am unable to reproduce the "reserved word" error and everything works fine when deploying the template from GitHub. Are able to send me more info about it?
