### ISSUE TITLE
Lab 1 - Copy table from NYCDataSets database to Synapse Analytics data warehouse.

### ISSUE THREAD

**Issue by prkapur** [fabragaMS/ADPE2E#8]
This is a fantastic workshop and very helpful. 

I went the through the setup in Lab 0 and Lab 1 and was checking where I could find the steps to load NYCDataSets into OperationalSQL_NYCDataSets SQL Database.  

Without this, I cant trigger the datafactory pipleine to copy the table from OperationalSQL into SynapseSQL. 

Thanks

**Comment by fabragaMS** [comment]
Hi prkapur, 

I'm glad you are enjoying the content. The NYCDataSets database is created when you deploy the ARM template for the workshop and it is initialised from a bacpac file that already contains all the necessary tables used during the labs. If you are interested in understanding how it happens, check the azuredeploy.json ARM template (https://raw.githubusercontent.com/fabragaMS/ADPE2E/master/Deploy/azuredeploy.json) and search for "NYCDataSets". You will find there how the database is created and initialised. Let me know how you go and whether this is still an issue. Thank you!

**Comment by prkapur** [comment]
@fabragaMS - I will review this step again. I have used the "Deploy To Azure" button in Lab 0: Deploy Azure Services. 

It spun up an empty instance of the NYCDataSets database with no tables and no data i.e I believe it did not restore the backup file.

I'll run this again and see if there are any errors in deployment and get back. Thanks.

**Comment by prkapur** [comment]
I ran the deployment again and looks like the NYCDataSets database has been loaded correctly this time. I dont know what the root cause could have been the first time, and its worked this time.

Thanks Plenty!
